name: Commons
version: "${version}"
main: ru.shk.commons.Commons
api-version: '1.20'
load: STARTUP
authors: [ shoker137 ]
softdepend:
  - MySQLAPI
  - FastAsyncWorldEdit
commands:
  commonsbukkit:
    permission: commons.admin
libraries:
  - net.kyori:adventure-platform-bungeecord:4.3.2